StoreProject/Models/Part.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StoreProject.Models
{

    // part table 
    public class Part
    {


        // Fields 
        public long PartId { get; set; }
        [Required]
        public String name { get; set; }
        [Required]
        public String Description { get; set; }
        public bool packed { get; set; } 
        public String picture { get; set; }

        //Foreign Key  

       public virtual ICollection<Piece> pieces { get; set; }




     
    }
}

StoreProject/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreProject.Models;

namespace StoreProject.Controllers
{
    public class PartController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: /Part/
        public ActionResult Index()

        {

            return View(db.Part.ToList());
        }

        // GET: /Part/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Part.Find(id);
            
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // GET: /Part/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Part/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PartId,name,Description,packed,picture")] Part part, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                //no part yet 
                if (ImageFile != null)
                {
                    part.picture= System.IO.Path.GetExtension(ImageFile.FileName);
                   
                }
                db.Part.Add(part);
                db.SaveChanges();

                // part exist
                if (ImageFile != null)
                {
                    string picName = part.PartId + System.IO.Path.GetExtension(ImageFile.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/images/part"), picName);
                    ImageFile.SaveAs(path);
                }

                long id = part.PartId;
                return RedirectToAction("addPiece", new { id });
                
            }

            return View(part);
        }

        // Add Piece to a part 
        public ActionResult addPiece(long? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Part.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }

            int count;
            if (part.packed)
            {

                 count = (from p in db.Piece where p.PartId == id  select (int?) p.quantity).Sum()?? 0;
                

            }
            else
            {

               count = (int?)part.pieces.Count()?? 0;
            }

           



            ViewData["Stock"] = count;
            ViewData["SelectedPart"] = part;

            return View();
        }

        //Create the Piece
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePiece([Bind(Include = "PartId,location,owner,status,quantity")] Piece piece)
        {
            if (ModelState.IsValid)
            {
               

                db.Piece.Add(piece);
                db.SaveChanges();
                long id = (long)piece.Id;

                return RedirectToAction("QrGenerate", new { id });
            }

            return RedirectToAction("Index");
        }

        // Generating the Qr
        public ActionResult QrGenerate(long id)
        {

            Piece piece = db.Piece.Find(id);
            return View(piece);
        }

        // GET: /Part/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Part.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // POST: /Part/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PartId,name,Description,packed,picture")] Part part, HttpPostedFileBase ImageFile, String Remove)
        {
            if (ModelState.IsValid)
            {
                if (string.Equals(Remove, "Remove"))
                {
                    try
                    {
                        string path = "~/images/part/" + part.PartId + part.picture;
                        System.IO.File.Delete(path);
                    }
                    catch (Exception) { }
                    part.picture = null;
                    db.Entry(part).State = EntityState.Modified;
                }
                else
                {
                    if (ImageFile != null)
                    {
                        //
                        part.picture = System.IO.Path.GetExtension(ImageFile.FileName);
                        string picName = part.PartId + part.picture;
                        string path = System.IO.Path.Combine(Server.MapPath("~/images/part"), picName);
                        ImageFile.SaveAs(path);
                        db.Entry(part).State = EntityState.Modified;
                    }
                    else
                    {
                        Part partTemp = db.Part.Find(part.PartId);
                        partTemp.name = part.name;
                        partTemp.Description = part.Description;


                        db.Entry(partTemp).State = EntityState.Modified;

                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(part);
        }

        // GET: /Part/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Part part = db.Part.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // POST: /Part/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Part part = db.Part.Find(id);
            db.Part.Remove(part);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreProject/Views/Part/Create.cshtml
@model StoreProject.Models.Part

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Part", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Part</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new  { @cols= "80" , @rows= "4"})
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.packed, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.packed)
                @Html.ValidationMessageFor(model => model.packed)
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.picture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="ImageFile" type="file"  />
            </div>
        </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StoreProject/Views/Part/Delete.cshtml
@model StoreProject.Models.Part

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @if (Model.picture != null)
            {
                <img src="~/images/part/@Model.PartId@Model.picture" height="200" />
            }
            else
            {
                <img src="~/images/part/No_Image.png" height="200" />
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoreProject/Views/Part/Details.cshtml
@model StoreProject.Models.Part

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Part</h4>
	<hr />
    <dl class="dl-horizontal">
        
        <dd>
            @if (Model.picture != null)
            {
                <img src="~/images/part/@Model.PartId@Model.picture" height="200" />
            }
            else
            {
                <img src="~/images/part/No_Image.png" height="200" />
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.packed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.packed)
        </dd>


    </dl>

    <h4> Pieces </h4>
    @*---------------------------------------------------------*@

    <table class="table">
        <tr>
            <th>
                @Html.Label("#")
            </th>
            <th>
                @Html.Label("Owner")
            </th>
            <th>
                @Html.Label("Location")
            </th>
            <th>
                @Html.Label("Status")
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model.pieces)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.owner)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>

                @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.PartId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.PartId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.PartId }) |
                    @Html.ActionLink("Add Pieces", "addPiece", new { id = item.PartId })
                </td>*@
            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PartId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoreProject/Views/Part/Edit.cshtml
@model StoreProject.Models.Part

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Part", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Part</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.PartId)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.packed, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.packed)
                @Html.ValidationMessageFor(model => model.packed)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="ImageFile" type="file" />
                <input id="Remove" name="Remove" type="checkbox" value="Remove" />
                <label for="Remove">&nbsp;Remove Picture?</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StoreProject/Views/Part/Index.cshtml
@model IEnumerable<StoreProject.Models.Part>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.packed)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.packed)
        </td>
       
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PartId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PartId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PartId }) |
            @Html.ActionLink("Add Pieces", "addPiece", new { id = item.PartId })
        </td>
    </tr>
}

</table>

StoreProject/Views/Part/QrGenerate.cshtml
@model StoreProject.Models.Piece
@{
    ViewBag.Title = "QrGenerate";
}

<h2>QrCode</h2>
<div hidden>
@Html.TextBox("id",Model.Id)

</div>

<div id="qr">  </div>


@section scripts{
@Scripts.Render("~/bundles/jqueryqr")
<script type="text/javascript">

   var x = document.getElementById("id").value 
    jQuery('#qr').qrcode({

        text: x,
        width: 64,
        height: 64
       


    });
   
    
</script>
<script type="text/javascript">

   
    function printcontent() {

      
        var restore = document.getElementById("links").innerHTML;
        document.getElementById("links").innerHTML = document.getElementById("clean").innerHTML;
        window.print();
        document.getElementById("links").innerHTML = restore;
        


       


    }



    </script>
    }

<div id="clean">

</div>

<div id="links">
    <h4></h4>



    <p>

        <div>
            <input type="button" value="Print" id="btnPrint" class="btn btn-default" onclick="printcontent()" />

        </div>

        @Html.ActionLink("Back to Part", "addPiece", new { id = Model.PartId }) |
        @Html.ActionLink("Back to List", "Index")

    </p>

</div>

StoreProject/Views/Part/addPiece.cshtml
@model StoreProject.Models.Piece
@using StoreProject.Models
@{
    ViewBag.Title = "addPiece";
}

<h2>Add Pieces</h2>

<div>

    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @if (((Part)ViewData["SelectedPart"]).picture != null)
            {
                <img src="~/images/part/@(((Part)ViewData["SelectedPart"]).PartId)@(((Part)ViewData["SelectedPart"]).picture)" height="200" />
            }
            else
            {
                <img src="~/images/part/No_Image.png" height="200" />
            }
        </dd>
        <dt>
           <label>Name: </label>
        </dt>

        <dd>
            <label> @Html.Label((((Part)ViewData["SelectedPart"]).name).ToString()) </label> 
        </dd>
        <dt>
            <label>Description: </label>
        </dt>

        <dd>
            <label> @Html.Label((((Part)ViewData["SelectedPart"]).Description).ToString()) </label>
        </dd>

        <dt>
            <label> Stock: </label>
        </dt>

        <dd>
            <label> @Html.Label((((int)ViewData["Stock"])).ToString()) </label>
        </dd>

       
        </dl>
</div>

<div>

    @using (Html.BeginForm("CreatePiece", "Part"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4> Piece </h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.location, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.location)
                    @Html.ValidationMessageFor(model => model.location)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.owner, new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.TextBoxFor(model => model.owner, new { @cols = "80", @rows = "4" })
                    @Html.ValidationMessageFor(model => model.owner)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.status, new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DropDownListFor(model => model.status, new List<SelectListItem>{
                         new SelectListItem() {Text ="New", Value="New"},
                         new SelectListItem() {Text ="Used", Value="Used"},
                         new SelectListItem() {Text ="Dameged", Value="Dameged"}})
                    @Html.ValidationMessageFor(model => model.status)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PartId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.TextBoxFor(model => model.PartId, new { @cols = "80", @rows = "4", Value = ((Part)ViewData["SelectedPart"]).PartId, @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.PartId)
                </div>
            </div>
            @if ((((Part)ViewData["SelectedPart"]).packed))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.quantity, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @Html.TextBoxFor(model => model.quantity, new { @cols = "80", @rows = "4"})
                        @Html.ValidationMessageFor(model => model.PartId)
                    </div>
                </div>
            }
            <div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-5">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>


            </div>
           

        </div>

    }

</div>